site_name: Shunya KV Documentation
site_url: https://somesh-m.github.io/shunyakv/docs/
site_description: ShunyaKV is a high-performance shared-nothing key-value store built with C++17, Seastar, designed for low-latency caching and high-throughput workloads.
site_author: Somesh Mohan

nav:
  - Home: index.md
  - Documentation:
      - Architecture: architecture/arch_dpdk.md
      - Client Design: dpdk_client_connection.md
      - Performance: perf.md
      - Installation: installation.md
plugins:
  - search
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil
    view: material/eye
  font:
    text: Roboto Mono
  palette:
  # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.sharing

extra:
  version:
    provider: mike

repo_url: https://github.com/somesh-m/shunya-kv/
edit_uri: edit/main/docs/
